{% set name = "metatensor-operations" %}
{% set version = "0.3.4" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/metatensor_operations-{{ version }}.tar.gz
  sha256: 448c155e5d4ac7ad7bdf56a6d0883f641622d54d4357f50b2149b2cb2ad8d66a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=75
    - packaging >=23
    - pip
  run:
    - python >={{ python_min }}
    - python-metatensor-core >=0.1.10,<0.2.0

test:
  imports:
    - metatensor
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/metatensor/metatensor
  summary: Operations to manipulate metatensor data types
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://docs.metatensor.org

extra:
  recipe-maintainers:
    - HaoZeke
    - PicoCentauri
    - Luthaf
